pipeline:

  install:
    image: node:10
    commands:
      - npm install
    secrets: [ npm_token ]

  build:
    image: meltwaterfoundation/drone-serverless:1.41.1
    commands:
      - ./scripts/build
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
      - google_client_id
      - google_client_secret
      - google_refresh_token
    when:
      event: [ push ]
      branch: [ master ]

  build-python:
    image: meltwaterfoundation/drone-boto3
    commands:
      - ./scripts/build-python
    when:
      event: [ push ]
      branch: [ master ]

  zip-package:
    image: meltwaterfoundation/drone-serverless:1.41.1
    commands:
      - ./scripts/zip-package
    when:
      event: [ push ]
      branch: [ master ]

  deploy:
    image: meltwaterfoundation/drone-serverless:1.41.1
    commands:
      - npm run deploy
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event: [ push ]
      branch: [ master ]