#!/usr/bin/env bash
set -e # Exit on any child process error

source ./scripts/setup_env

mkdir -p dist

echo "Transpile ES6 to CJS"
npm i
npm run transpile -- --ignore spec.js

echo "Preparing infrastructure code for AWS account"
cat ./infrastructure/config.json | node_modules/mustache/bin/mustache - ./infrastructure/cloudformation.yaml > ./dist/cloudformation.yaml

echo "Preparing production dependencies"
rm -rf ./node_modules
npm install --production
pushd ./dist/cjs
ln -s ../../node_modules/
popd

echo "Packaging code"
pushd dist/cjs
zip -q -r ../youtube-upload.zip .
