#!/usr/bin/env bash
set -e # Exit on any child process error

mkdir -p dist/cjs

cp old-lambda/src/function.py ./dist/cjs/youtube-upload.py

echo "Packaging code"
pushd dist/cjs
zip -q -r ../youtube-upload.zip .
