#!/usr/bin/env bash
set -e # Exit on any child process error

echo "Running Python Build"
pushd dist/cjs

echo "Upgrading Pip"
pip install --upgrade pip

echo "Installing Python Virtual Environment"
pip3 install virtualenv

echo "Creating Python Virtual Environment"
python3 -m venv env

echo "Activating Python Virtual Environment"
source env/bin/activate

echo "Installing Python Dependencies"
pip3 install -r requirements.txt -t .
pip3 install slackclient

popd