#!/usr/bin/env bash
set -e # Exit on any child process error

npm run clean

mkdir -p dist/cjs

npm i -g mustache

echo "Preparing infrastructure code for AWS account"
echo "{\"GOOGLE_CLIENT_ID\":\"${GOOGLE_CLIENT_ID}\",
       \"GOOGLE_CLIENT_SECRET\":\"${GOOGLE_CLIENT_SECRET}\",
       \"AWS_ACCESS_KEY_ID\":\"${AWS_ACCESS_KEY_ID}\",
       \"AWS_SECRET_ACCESS_KEY\":\"${AWS_SECRET_ACCESS_KEY}\"}" | mustache - ./infrastructure/config.json > ./dist/config.json
cat ./dist/config.json | mustache - ./infrastructure/cloudformation.yaml > ./dist/cloudformation.yaml

echo "Copying Code to Dist"
cp ./src/function.py ./dist/cjs/youtube-upload.py
cp ./src/requirements.txt ./dist/cjs/requirements.txt